#baseURL = "https://peaceful-lamport-4f7c91.netlify.com/"
baseURL = "https://zktkz.github.io/"
languageCode = "en-us"
title = "tazik.sh"
theme = "hugo-theme-console"
#theme = "hugo-vitae"

[params]
  [[params.navlinks]]
  name = "posts"
  url = "posts/"
