# baseURL = "https://peaceful-lamport-4f7c91.netlify.com/"
baseURL = "/"
languageCode = "en-us"
title = "Tazikistan"
theme = "hugo-theme-console"

[params]
  [[params.navlinks]]
  name = "posts"
  url = "posts/"
